version: '3.3'

services:
  sas-dashboard:
    build: .
    container_name: sas-dashboard
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=change_this_to_something_secure
      - DB_PATH=/app/data/payments.db
      - SAS_API_IP=193.43.140.218
      - SAS_ADMIN_USER=top100
      - SAS_ADMIN_PASS=omar@123
      - SPECIAL_LOGIN_USER=maram
      - SPECIAL_LOGIN_PASS=m@123
      - WEBHOOK_URL=https://your-n8n-webhook-url.com
